on:
  push:
    branches: master

name: blogdown

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: install imagemagick
        run: |
          brew install cargo
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: |
           Rscript R/install.R
           
      